name: Execução manual

on:
  workflow_dispatch:

jobs:
  run_parent:
    runs-on: ubuntu-latest
    container:
      image: node
    env:
      USER: ${{ secrets.USER }}

    steps:
      - 
        name: TESTE
        run: | 
          echo "CLIENTE -> $USER"
          echo "SECRET -> ${{ secrets.USER }}"
